remote_theme: dieghernan/chulapa

# Find errors on this file with http://www.yamllint.com/

# Chulapa docs: https://dieghernan.github.io/chulapa/docs/02-config

# A. Site Settings /SEO options
locale                  : es-ES
title                   : Mi Blog    
subtitle                : Bienvenido
description             : Blog personal, aquí encontrarás mi contenido en español
baseurl                 : /blog-es
timezone                : Europe/Madrid

# SEO
og_image                :     #default[author.avatar (see below)] or [github-avatar]
twitter_site            : dhernangomez
author:
  name                  : dieghernan
  avatar                : https://github.com/dieghernan.png
  location              :  "Madrid, Spain"
  links:                
    - url:  https://github.com/dieghernan/
      icon: fab fa-github

# Web tracking 
gtag_id                 :  


# Search providers
search:
  label: Búsqueda
  landing_page          : /buscar
  provider              : algolia 
  algolia_logo          : true 
algolia:                                                                   
  application_id        : "KOIKA5PDQO"
  index_name            : "blog_esp"
  search_only_api_key   : "7f1fe42bef3f03458cb3a911ebc7e0ac"
  files_to_exclude:       
    - _layouts/*.html
    - _includes/*.html
  extensions_to_index:     
    - html
    - md
  searchableAttributes:                                                    
    - title                                                                    
    - headings                                                                 
    - unordered(content)                                                       
    - unordered(subtitle)                                                      
    - unordered(categories)                                                    
    - unordered(collection)                                                    
    - unordered(tags) 
  customRanking:            #Optional
    - desc(include_on_search)
    - desc(title)
    - desc(content) 
    - desc(subtitle)
    
# B. Navigation
# Configure your navbar and the footer of your site

# Navbar: 
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  style     :  #default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  expand    :  # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title   :  Inicio
    img     : https://github.com/dieghernan.png
  nav:
  - title   : Blog
    url     : /blog/
  - title   : Extras
    child   :
      - title : Tags
        url   : /tags
      - title : Categories
        url   : /categories
      - title : Archive
        url   : /archive
      - title : Current skin
        url   : /current-skin
  - title   : One World - mi otro sitio 🇬🇧
    url     : https://dieghernan.github.io/

#Social links to be placed on your site footer
footer:
  links:
    - label: "RSS"
      icon: "fa fa-rss"
      url:  "./atom.xml"
    - label: Stack Overflow
      icon: fab fa-stack-overflow
      url: https://stackoverflow.com/users/7877917/dieghernan
    - label: WikiCommons
      icon: fab fa-wikipedia-w
      url: https://commons.wikimedia.org/wiki/Special:ListFiles?limit=50&user=dieghernan84
    - label: Github
      icon: fab fa-github
      url: https://github.com/dieghernan/
    - label: Carto
      icon: far fa-dot-circle
      url: https://dieghernan.carto.com/
    - label: "RPubs"
      icon: "fab fa-r-project"
      url: "https://rpubs.com/dieghernan"
  
# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
 - url : https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700&display=swap

# Theme and colors
chulapa-skin: 
  highlight     : 
  vars          :    
    font-family-base: Roboto, sans-serif
    headings-font-family: Montserrat, sans-serif
    font-family-monospace: Roboto Mono, monospace
    white: white
    primary: "#1565c0"
    body-bg: white
    navbar-chulapa-bg-color: white 
    navbar-chulapa-active-color: "#2962ff"
    footer-chulapa-icon-color: "#1565c0"
    footer-chulapa-icon-hover-color: transparent
    h1-font-size: 2.25rem
    h2-font-size: 1.5rem
    h3-font-size: 1.25rem
    h4-font-size: 1rem
    h5-font-size: 1rem
    h6-font-size: 1rem
    
    
# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: "/blog/page:num/"
paginator_maxnum: 3  #default[3] Custom: max of number to be displayed on the paginator

# Collections https://jekyllrb.com/docs/step-by-step/09-collections/
collections:
collections_dir     : 
permalink           : /:year:month:day_:title/


# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
      cloudtag_url        : /tags #This #This is where the link on categories would redirect
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Blog
          url: /blog/
  
# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

